# Generated by Django 5.1.13 on 2025-10-19 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Заголовок"
                    ),
                ),
                (
                    "summary",
                    models.TextField(blank=True, verbose_name="Краткое описание"),
                ),
                ("body", models.TextField(blank=True, verbose_name="Текст")),
                (
                    "hashtags",
                    models.JSONField(blank=True, default=list, verbose_name="Хэштеги"),
                ),
                (
                    "sources",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Источники"
                    ),
                ),
                (
                    "editor_comment",
                    models.TextField(
                        blank=True,
                        help_text="Инструкции для модели перед рерайтом.",
                        verbose_name="Комментарий редактора",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("rewriting", "Рерайт"),
                            ("ready", "Готов к публикации"),
                            ("published", "Опубликован"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "prompt_snapshot",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Сообщения, отправленные в модель при последнем рерайте.",
                        verbose_name="Последний промпт",
                    ),
                ),
                (
                    "last_rewrite_payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Сырые данные ответа модели.",
                        verbose_name="Результат рерайта",
                    ),
                ),
                (
                    "last_rewrite_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата последнего рерайта"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stories",
                        to="projects.project",
                        verbose_name="Проект",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сюжет",
                "verbose_name_plural": "Сюжеты",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="RewriteTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        default="openai", max_length=50, verbose_name="Провайдер"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает"),
                            ("running", "В работе"),
                            ("success", "Успех"),
                            ("failed", "Ошибка"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "prompt_messages",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Сообщения, отправленные модели.",
                        verbose_name="Промпт",
                    ),
                ),
                (
                    "editor_comment",
                    models.TextField(blank=True, verbose_name="Комментарий редактора"),
                ),
                (
                    "result",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Результат"
                    ),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="Ошибка")),
                (
                    "response_id",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="ID ответа"
                    ),
                ),
                (
                    "attempts",
                    models.PositiveIntegerField(default=0, verbose_name="Попытки"),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Начато"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Завершено"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rewrite_tasks",
                        to="stories.story",
                        verbose_name="Сюжет",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задача рерайта",
                "verbose_name_plural": "Задачи рерайта",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="StoryPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(default=0, verbose_name="Позиция"),
                ),
                (
                    "added_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Добавлен"),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="story_posts",
                        to="projects.post",
                        verbose_name="Пост",
                    ),
                ),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="story_posts",
                        to="stories.story",
                        verbose_name="Сюжет",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пост сюжета",
                "verbose_name_plural": "Посты сюжетов",
                "ordering": ("position", "id"),
                "unique_together": {("story", "post")},
            },
        ),
        migrations.AddField(
            model_name="story",
            name="posts",
            field=models.ManyToManyField(
                related_name="stories",
                through="stories.StoryPost",
                to="projects.post",
                verbose_name="Посты",
            ),
        ),
    ]
