# Generated by Django 5.1.13 on 2025-10-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0003_rewrite_presets"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="image_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="story_images/",
                verbose_name="Прикреплённое изображение",
            ),
        ),
        migrations.AddField(
            model_name="story",
            name="image_prompt",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Последний промпт, по которому было сгенерировано изображение.",
                verbose_name="Описание изображения",
            ),
        ),
    ]
