# Generated by Django 5.1.13 on 2026-01-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0007_storyimage_library_asset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storyimage",
            name="source_kind",
            field=models.CharField(
                choices=[
                    ("generated", "Сгенерировано"),
                    ("upload", "Загрузка"),
                    ("source", "Источник"),
                    ("library", "Медиабиблиотека"),
                ],
                default="generated",
                max_length=20,
                verbose_name="Источник",
            ),
        ),
    ]
