# Generated by Django 5.1.13 on 2025-10-19 14:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": "Проект",
                "verbose_name_plural": "Проекты",
                "ordering": ("name",),
                "unique_together": {("owner", "name")},
            },
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Название"
                    ),
                ),
                (
                    "telegram_id",
                    models.BigIntegerField(
                        help_text="Идентификатор канала или чата (peer id).",
                        verbose_name="Telegram ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        help_text="Публичный username канала без @",
                        max_length=255,
                        verbose_name="Username",
                    ),
                ),
                (
                    "invite_link",
                    models.CharField(
                        blank=True,
                        help_text="Ссылка-приглашение, если канал приватный.",
                        max_length=512,
                        verbose_name="Инвайт ссылка",
                    ),
                ),
                (
                    "include_keywords",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text=(
                            "Посты проходят фильтр, если содержат одно из слов "
                            "(регистронезависимо). Оставьте пустым для отключения."
                        ),
                        verbose_name="Whitelist ключевых слов",
                    ),
                ),
                (
                    "exclude_keywords",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Посты игнорируются, если содержат слова из списка.",
                        verbose_name="Blacklist ключевых слов",
                    ),
                ),
                (
                    "deduplicate_text",
                    models.BooleanField(
                        default=True, verbose_name="Дедупликация текста"
                    ),
                ),
                (
                    "deduplicate_media",
                    models.BooleanField(
                        default=True, verbose_name="Дедупликация медиа"
                    ),
                ),
                (
                    "retention_days",
                    models.PositiveIntegerField(
                        default=7,
                        help_text=(
                            "По истечении срока медиафайлы должны быть удалены "
                            "фоновым процессом."
                        ),
                        verbose_name="Срок хранения (дней)",
                    ),
                ),
                (
                    "last_synced_id",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Используется для инкрементального сбора.",
                        null=True,
                        verbose_name="Последний обработанный пост",
                    ),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Последний сбор"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="projects.project",
                        verbose_name="Проект",
                    ),
                ),
            ],
            options={
                "verbose_name": "Источник",
                "verbose_name_plural": "Источники",
                "ordering": ("project", "title"),
                "unique_together": {("project", "telegram_id")},
            },
        ),
        migrations.CreateModel(
            name="SourceSyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Старт"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Завершение"
                    ),
                ),
                (
                    "fetched_messages",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Получено сообщений"
                    ),
                ),
                (
                    "skipped_messages",
                    models.PositiveIntegerField(default=0, verbose_name="Пропущено"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "Успех"),
                            ("partial", "Частично"),
                            ("failed", "Ошибка"),
                        ],
                        default="ok",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="Ошибка")),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_logs",
                        to="projects.source",
                        verbose_name="Источник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Лог синхронизации источника",
                "verbose_name_plural": "Логи синхронизации источников",
                "ordering": ("-started_at",),
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telegram_id", models.BigIntegerField(verbose_name="Telegram ID")),
                ("message", models.TextField(blank=True, verbose_name="Текст")),
                (
                    "raw",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Сырые данные"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новый"),
                            ("processing", "В обработке"),
                            ("used", "Использован"),
                            ("deleted", "Удалён"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("posted_at", models.DateTimeField(verbose_name="Дата публикации")),
                (
                    "collected_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Собран"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
                ),
                (
                    "has_media",
                    models.BooleanField(default=False, verbose_name="Есть медиа"),
                ),
                (
                    "media_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Тип медиа"
                    ),
                ),
                (
                    "media_path",
                    models.CharField(
                        blank=True, max_length=512, verbose_name="Путь к медиа"
                    ),
                ),
                (
                    "text_hash",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Хэш текста"
                    ),
                ),
                (
                    "media_hash",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Хэш медиа"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="projects.project",
                        verbose_name="Проект",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="projects.source",
                        verbose_name="Источник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пост",
                "verbose_name_plural": "Посты",
                "ordering": ("-posted_at",),
                "indexes": [
                    models.Index(
                        fields=["source", "status"],
                        name="projects_po_source__4875c9_idx",
                    ),
                    models.Index(
                        fields=["project", "status"],
                        name="projects_po_project_9aa3da_idx",
                    ),
                ],
                "unique_together": {("source", "telegram_id")},
            },
        ),
    ]
