# Generated by Django 5.1.13 on 2025-10-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="publish_target",
            field=models.CharField(
                blank=True,
                help_text="Например, @my_channel или ссылка на чат",
                max_length=255,
                verbose_name="Целевой канал",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="retention_days",
            field=models.PositiveIntegerField(
                default=90,
                help_text="Посты старше указанного срока удаляются из ленты проекта.",
                verbose_name="Срок хранения постов (дней)",
            ),
        ),
    ]
