# Generated by Django 5.1.13 on 2025-10-26 07:32

from django.db import migrations, models


def populate_post_language(apps, schema_editor):
    Post = apps.get_model("projects", "Post")
    from projects.services.language import detect_language

    for post in Post.objects.all().iterator():
        code = detect_language(post.message)
        if post.language != code:
            Post.objects.filter(pk=post.pk).update(language=code)


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_project_publish_target_project_retention_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="language",
            field=models.CharField(
                choices=[
                    ("ru", "Русский"),
                    ("en", "Английский"),
                    ("unknown", "Не определён"),
                ],
                default="unknown",
                max_length=16,
                verbose_name="Язык",
            ),
        ),
        migrations.RunPython(populate_post_language, migrations.RunPython.noop),
    ]
