# Generated by Django 5.1.13 on 2025-10-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_post_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="telegram_id",
            field=models.BigIntegerField(
                blank=True,
                help_text="Опционально: числовой идентификатор канала (peer id).",
                null=True,
                verbose_name="Telegram ID",
            ),
        ),
    ]
