# Generated by Django 5.1.13 on 2025-10-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_limit_image_sizes"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="rewrite_model",
            field=models.CharField(
                choices=[
                    ("gpt-4o-mini", "gpt-4o-mini"),
                    ("gpt-4o", "gpt-4o"),
                    ("gpt-4.1-mini", "gpt-4.1-mini"),
                ],
                default="gpt-4o-mini",
                help_text="Выберите модель GPT, которая будет использоваться при переписывании текста.",
                max_length=100,
                verbose_name="Модель рерайта",
            ),
        ),
    ]
