# Generated by Django 5.1.13 on 2025-11-07 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0009_projectpromptconfig"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebPreset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Системное имя"),
                ),
                (
                    "version",
                    models.CharField(
                        default="1.0.0", max_length=50, verbose_name="Версия"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Название"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "schema_version",
                    models.PositiveIntegerField(default=1, verbose_name="Версия схемы"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("active", "Активный"),
                            ("broken", "Сломан"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "checksum",
                    models.CharField(max_length=64, verbose_name="Контрольная сумма"),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Конфигурация"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
                ),
            ],
            options={
                "verbose_name": "Веб-пресет",
                "verbose_name_plural": "Веб-пресеты",
                "ordering": ("name", "version"),
            },
        ),
        migrations.AlterUniqueTogether(
            name="post",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="post",
            name="canonical_url",
            field=models.URLField(
                blank=True, max_length=1000, verbose_name="Канонический URL"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="content_hash",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="Хэш контента"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="content_html",
            field=models.TextField(blank=True, verbose_name="HTML контент"),
        ),
        migrations.AddField(
            model_name="post",
            name="content_md",
            field=models.TextField(blank=True, verbose_name="Markdown контент"),
        ),
        migrations.AddField(
            model_name="post",
            name="external_id",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Внешний ID"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="external_metadata",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Метаданные источника"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="images_manifest",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Изображения"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="origin_type",
            field=models.CharField(
                choices=[("telegram", "Telegram"), ("web", "Web")],
                default="telegram",
                max_length=20,
                verbose_name="Тип источника",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="raw_html",
            field=models.TextField(blank=True, verbose_name="Сырый HTML"),
        ),
        migrations.AddField(
            model_name="post",
            name="source_url",
            field=models.URLField(
                blank=True, max_length=1000, verbose_name="URL источника"
            ),
        ),
        migrations.AddField(
            model_name="source",
            name="type",
            field=models.CharField(
                choices=[("telegram", "Telegram"), ("web", "Web")],
                default="telegram",
                max_length=20,
                verbose_name="Тип источника",
            ),
        ),
        migrations.AddField(
            model_name="source",
            name="web_last_status",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Статус последнего веб-сбора"
            ),
        ),
        migrations.AddField(
            model_name="source",
            name="web_last_synced_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Последний веб-сбор"
            ),
        ),
        migrations.AddField(
            model_name="source",
            name="web_preset_snapshot",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Конфигурация, с которой работает источник (фиксируется при импорте).",
                verbose_name="Снимок пресета",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="telegram_id",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="Telegram ID"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["origin_type", "source"], name="projects_po_origin__d74520_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["source_url"], name="projects_po_source__0d3f8b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["canonical_url"], name="projects_po_canonic_9b2aba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["content_hash"], name="projects_po_content_76bb89_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="post",
            constraint=models.UniqueConstraint(
                condition=models.Q(("origin_type", "telegram")),
                fields=("source", "telegram_id"),
                name="post_unique_telegram_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="post",
            constraint=models.UniqueConstraint(
                condition=models.Q(("origin_type", "web")),
                fields=("source", "external_id"),
                name="post_unique_web_source_external",
            ),
        ),
        migrations.AddConstraint(
            model_name="webpreset",
            constraint=models.UniqueConstraint(
                fields=("name", "version"), name="web_preset_unique_version"
            ),
        ),
        migrations.AddField(
            model_name="source",
            name="web_preset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sources",
                to="projects.webpreset",
                verbose_name="Пресет веб-парсера",
            ),
        ),
    ]
