# Generated by Django 5.1.13 on 2025-11-11 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0010_webpreset_alter_post_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="locale",
            field=models.CharField(
                default="ru_RU",
                help_text="Используется для форматирования даты и времени в подсказках.",
                max_length=20,
                verbose_name="Локаль",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="time_zone",
            field=models.CharField(
                default="UTC",
                help_text="Например Europe/Moscow или UTC+03:00. Определяет локальное время проекта.",
                max_length=50,
                verbose_name="Часовой пояс",
            ),
        ),
    ]
