# Generated by Django 5.1.13 on 2025-11-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0012_project_collector_intervals_and_post_ordering"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ("-collected_at", "-posted_at"),
                "verbose_name": "Пост",
                "verbose_name_plural": "Посты",
            },
        ),
        migrations.RenameIndex(
            model_name="post",
            new_name="projects_po_project_bd0e8d_idx",
            old_name="post_project_collected_idx",
        ),
        migrations.AlterField(
            model_name="project",
            name="collector_telegram_interval",
            field=models.PositiveIntegerField(
                default=300,
                help_text="Как часто опрашивать Telegram-источники (не менее 30 секунд).",
                verbose_name="Интервал Telegram (сек)",
            ),
        ),
    ]
