# Generated by Django 5.1.13 on 2025-11-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0015_update_image_size_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="image_model",
            field=models.CharField(
                choices=[
                    ("gpt-image-1", "gpt-image-1"),
                    ("dall-e-3", "dall-e-3"),
                    ("yandex-art", "yandex-art"),
                ],
                default="gpt-image-1",
                max_length=100,
                verbose_name="Модель генерации изображений",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="rewrite_model",
            field=models.CharField(
                choices=[
                    ("gpt-4o-mini", "gpt-4o-mini"),
                    ("gpt-4o", "gpt-4o"),
                    ("gpt-4.1-mini", "gpt-4.1-mini"),
                    ("gpt-5", "gpt-5"),
                    ("yandexgpt-lite", "yandexgpt-lite"),
                    ("yandexgpt", "yandexgpt"),
                ],
                default="gpt-4o-mini",
                help_text="Выберите модель GPT, которая будет использоваться при переписывании текста.",
                max_length=100,
                verbose_name="Модель рерайта",
            ),
        ),
    ]
