# Generated by Django 5.1.13 on 2025-11-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0016_alter_project_image_model_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="web_retry_base_delay",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Секунды до повторной попытки после ошибки (по умолчанию 30).",
                null=True,
                verbose_name="Базовая задержка ретрая (сек)",
            ),
        ),
        migrations.AddField(
            model_name="source",
            name="web_retry_max_attempts",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Переопределяет стандартное ограничение очереди (оставьте пустым, чтобы использовать дефолт).",
                null=True,
                verbose_name="Максимум попыток веб-задачи",
            ),
        ),
        migrations.AddField(
            model_name="source",
            name="web_retry_max_delay",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Верхняя граница экспоненциальной паузы между попытками (по умолчанию 900).",
                null=True,
                verbose_name="Макс. задержка ретрая (сек)",
            ),
        ),
    ]
