# Generated by Django 5.1.13 on 2025-12-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0019_project_public_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="image_prompt_model",
            field=models.CharField(
                choices=[
                    ("gpt-4o-mini", "gpt-4o-mini"),
                    ("gpt-4o", "gpt-4o"),
                    ("gpt-4.1-mini", "gpt-4.1-mini"),
                    ("gpt-5", "gpt-5"),
                    ("gpt-5o", "gpt-5o"),
                    ("gemini-1.5-flash", "gemini-1.5-flash"),
                    ("yandexgpt-lite", "yandexgpt-lite"),
                    ("yandexgpt", "yandexgpt"),
                ],
                default="gemini-1.5-flash",
                help_text="Модель для генерации рекомендованного промпта для изображения.",
                max_length=100,
                verbose_name="Модель для идеи изображения",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="image_model",
            field=models.CharField(
                choices=[("dall-e-3", "DALL-E 3"), ("yandex-art", "YandexART")],
                default="dall-e-3",
                max_length=100,
                verbose_name="Модель генерации изображений",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="image_quality",
            field=models.CharField(
                choices=[("hd", "hd"), ("standard", "standard")],
                default="standard",
                max_length=20,
                verbose_name="Качество изображения",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="image_size",
            field=models.CharField(
                choices=[
                    ("1024x1024", "1024x1024"),
                    ("1024x1792", "1024x1792"),
                    ("1792x1024", "1792x1024"),
                ],
                default="1024x1024",
                max_length=20,
                verbose_name="Размер изображения",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="rewrite_model",
            field=models.CharField(
                choices=[
                    ("gpt-4o-mini", "gpt-4o-mini"),
                    ("gpt-4o", "gpt-4o"),
                    ("gpt-4.1-mini", "gpt-4.1-mini"),
                    ("gpt-5", "gpt-5"),
                    ("gpt-5o", "gpt-5o"),
                    ("gemini-1.5-flash", "gemini-1.5-flash"),
                    ("yandexgpt-lite", "yandexgpt-lite"),
                    ("yandexgpt", "yandexgpt"),
                ],
                default="gpt-4o-mini",
                help_text="Выберите модель GPT, которая будет использоваться при переписывании текста.",
                max_length=100,
                verbose_name="Модель рерайта",
            ),
        ),
        migrations.AlterField(
            model_name="projectpromptconfig",
            name="image_prompt_template",
            field=models.TextField(
                blank=True,
                help_text="Шаблон для запроса в модель при подборе идеи иллюстрации.",
                verbose_name="Промпт для генерации идеи изображения",
            ),
        ),
    ]
