# Generated by Django 5.1.13 on 2025-12-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "projects",
            "0020_project_image_prompt_model_alter_project_image_model_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="image_model",
            field=models.CharField(
                choices=[
                    ("dall-e-3", "DALL-E 3"),
                    ("gemini-2.5-flash-image", "Gemini 2.5 Flash Image"),
                    ("gemini-3-pro-image-preview", "Gemini 3 Pro Image Preview"),
                    ("yandex-art", "YandexART"),
                ],
                default="dall-e-3",
                max_length=100,
                verbose_name="Модель генерации изображений",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="image_quality",
            field=models.CharField(
                choices=[
                    ("auto", "auto"),
                    ("high", "high"),
                    ("low", "low"),
                    ("medium", "medium"),
                    ("standard", "standard"),
                ],
                default="medium",
                max_length=20,
                verbose_name="Качество изображения",
            ),
        ),
    ]
