# Generated by Django 5.1.13 on 2026-01-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0025_project_members"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="image_prompt_model",
            field=models.CharField(
                choices=[
                    ("gpt-4o-mini", "gpt-4o-mini"),
                    ("gpt-4o", "gpt-4o"),
                    ("gpt-4.1", "gpt-4.1"),
                    ("gpt-4.1-mini", "gpt-4.1-mini"),
                    ("gpt-4.1-nano", "gpt-4.1-nano"),
                    ("gpt-5.2", "gpt-5.2"),
                    ("gpt-3.5-turbo", "gpt-3.5-turbo"),
                    ("gpt-3.5-turbo-0125", "gpt-3.5-turbo-0125"),
                    ("gpt-3.5-turbo-1106", "gpt-3.5-turbo-1106"),
                    ("gemini-1.5-flash", "gemini-1.5-flash"),
                    ("yandexgpt-lite", "yandexgpt-lite"),
                    ("yandexgpt", "yandexgpt"),
                ],
                default="gemini-1.5-flash",
                help_text="Модель для генерации рекомендованного промпта для изображения.",
                max_length=100,
                verbose_name="Модель для идеи изображения",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="rewrite_model",
            field=models.CharField(
                choices=[
                    ("gpt-4o-mini", "gpt-4o-mini"),
                    ("gpt-4o", "gpt-4o"),
                    ("gpt-4.1", "gpt-4.1"),
                    ("gpt-4.1-mini", "gpt-4.1-mini"),
                    ("gpt-4.1-nano", "gpt-4.1-nano"),
                    ("gpt-5.2", "gpt-5.2"),
                    ("gpt-3.5-turbo", "gpt-3.5-turbo"),
                    ("gpt-3.5-turbo-0125", "gpt-3.5-turbo-0125"),
                    ("gpt-3.5-turbo-1106", "gpt-3.5-turbo-1106"),
                    ("gemini-1.5-flash", "gemini-1.5-flash"),
                    ("yandexgpt-lite", "yandexgpt-lite"),
                    ("yandexgpt", "yandexgpt"),
                ],
                default="gpt-4o-mini",
                help_text="Выберите модель GPT, которая будет использоваться при переписывании текста.",
                max_length=100,
                verbose_name="Модель рерайта",
            ),
        ),
    ]
