# Generated by Django 5.1.13 on 2026-03-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0029_source_telegram_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="source_url",
            field=models.URLField(
                blank=True,
                help_text="Корневой URL для универсального веб-парсинга без пресетов.",
                verbose_name="URL сайта-источника",
            ),
        ),
        migrations.AddField(
            model_name="source",
            name="web_engine",
            field=models.CharField(
                choices=[("preset", "Preset"), ("watercrawl", "Watercrawl")],
                default="preset",
                max_length=20,
                verbose_name="Движок веб-сбора",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="origin_type",
            field=models.CharField(
                choices=[
                    ("telegram", "Telegram"),
                    ("web", "Web"),
                    ("manual", "Редакторский текст"),
                ],
                default="telegram",
                max_length=20,
                verbose_name="Тип источника",
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="type",
            field=models.CharField(
                choices=[
                    ("telegram", "Telegram"),
                    ("web", "Web"),
                    ("manual", "Редакторский текст"),
                ],
                default="telegram",
                max_length=20,
                verbose_name="Тип источника",
            ),
        ),
    ]
