# Generated by Django 5.1.13 on 2025-10-20 13:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WorkerTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("queue", models.CharField(max_length=50, verbose_name="Очередь")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="queued",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "priority",
                    models.SmallIntegerField(
                        default=0,
                        help_text="Чем меньше значение, тем выше приоритет обработки.",
                        verbose_name="Приоритет",
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Данные задачи"
                    ),
                ),
                (
                    "result",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Результат"
                    ),
                ),
                (
                    "attempts",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Выполненные попытки"
                    ),
                ),
                (
                    "max_attempts",
                    models.PositiveIntegerField(
                        default=3, verbose_name="Максимум попыток"
                    ),
                ),
                (
                    "available_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Когда задачу можно брать в работу.",
                        verbose_name="Доступна после",
                    ),
                ),
                (
                    "locked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Заблокирована в"
                    ),
                ),
                (
                    "locked_by",
                    models.CharField(blank=True, max_length=64, verbose_name="Воркер"),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Начата"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Завершена"
                    ),
                ),
                (
                    "last_error_code",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Код ошибки"
                    ),
                ),
                (
                    "last_error_message",
                    models.TextField(blank=True, verbose_name="Описание ошибки"),
                ),
                (
                    "last_error_payload",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Детали ошибки"
                    ),
                ),
                (
                    "base_retry_delay",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Начальное значение экспоненциальной задержки для ретраев.",
                        verbose_name="Базовая задержка ретрая (сек)",
                    ),
                ),
                (
                    "max_retry_delay",
                    models.PositiveIntegerField(
                        default=3600,
                        help_text="Верхняя граница задержки между попытками.",
                        verbose_name="Максимальная задержка ретрая (сек)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлена"),
                ),
            ],
            options={
                "verbose_name": "Фоновая задача",
                "verbose_name_plural": "Фоновые задачи",
                "ordering": ("priority", "available_at", "id"),
                "indexes": [
                    models.Index(
                        fields=["queue", "status", "available_at"],
                        name="core_worker_queue_63f7d5_idx",
                    ),
                    models.Index(
                        fields=["queue", "priority"],
                        name="core_worker_queue_da35c8_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkerTaskAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attempt_number",
                    models.PositiveIntegerField(verbose_name="Номер попытки"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "error_code",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Код ошибки"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Описание ошибки"),
                ),
                (
                    "error_payload",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Детали ошибки"
                    ),
                ),
                (
                    "duration_ms",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Длительность (мс)"
                    ),
                ),
                (
                    "will_retry",
                    models.BooleanField(default=False, verbose_name="Повтор будет"),
                ),
                (
                    "available_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Следующая попытка"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts_log",
                        to="core.workertask",
                        verbose_name="Задача",
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка выполнения задачи",
                "verbose_name_plural": "Попытки выполнения задач",
                "ordering": ("-created_at",),
            },
        ),
    ]
