# Generated by Django 5.1.13 on 2025-12-09 06:46

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="workertask",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["payload"], name="core_worker_payload_ae5108_gin"
            ),
        ),
    ]
