"""Shared constants used across the Paperbird project."""

from __future__ import annotations

DEFAULT_COLLECT_LIMIT = 100
REWRITE_MAX_ATTEMPTS = 3
OPENAI_DEFAULT_TEMPERATURE = 0.2
OPENAI_RESPONSE_FORMAT = {"type": "json_object"}

COLLECTOR_MAX_ATTEMPTS = 5
COLLECTOR_BASE_RETRY_DELAY = 30
COLLECTOR_MAX_RETRY_DELAY = 900

PUBLISH_MAX_ATTEMPTS = 4
PUBLISH_BASE_RETRY_DELAY = 45
PUBLISH_MAX_RETRY_DELAY = 1800

IMAGE_MAX_ATTEMPTS = 3
IMAGE_BASE_RETRY_DELAY = 30
IMAGE_MAX_RETRY_DELAY = 900

REWRITE_BASE_RETRY_DELAY = 20
REWRITE_MAX_RETRY_DELAY = 600

DEFAULT_QUEUE_MAX_ATTEMPTS = 5
DEFAULT_QUEUE_BASE_RETRY_DELAY = 10
DEFAULT_QUEUE_MAX_RETRY_DELAY = 3600
