"""Shared constants used across the Paperbird project."""

from __future__ import annotations

DEFAULT_COLLECT_LIMIT = 100
REWRITE_MAX_ATTEMPTS = 3
OPENAI_DEFAULT_TEMPERATURE = 0.2
OPENAI_RESPONSE_FORMAT = {"type": "json_object"}

COLLECTOR_MAX_ATTEMPTS = 5
COLLECTOR_BASE_RETRY_DELAY = 30
COLLECTOR_MAX_RETRY_DELAY = 900

PUBLISH_MAX_ATTEMPTS = 4
PUBLISH_BASE_RETRY_DELAY = 45
PUBLISH_MAX_RETRY_DELAY = 1800

IMAGE_MAX_ATTEMPTS = 3
IMAGE_BASE_RETRY_DELAY = 30
IMAGE_MAX_RETRY_DELAY = 900

REWRITE_BASE_RETRY_DELAY = 20
REWRITE_MAX_RETRY_DELAY = 600

REWRITE_DEFAULT_MAX_TOKENS = 1000

DEFAULT_QUEUE_MAX_ATTEMPTS = 5
DEFAULT_QUEUE_BASE_RETRY_DELAY = 10
DEFAULT_QUEUE_MAX_RETRY_DELAY = 3600

MAINTENANCE_MAX_ATTEMPTS = 3
MAINTENANCE_BASE_RETRY_DELAY = 60
MAINTENANCE_MAX_RETRY_DELAY = 3600

SOURCE_MAX_ATTEMPTS = 3
SOURCE_BASE_RETRY_DELAY = 120
SOURCE_MAX_RETRY_DELAY = 3600

IMAGE_MODEL_CHOICES = (
    ("gpt-image-1", "gpt-image-1"),
    ("dall-e-3", "dall-e-3"),
)

IMAGE_SIZE_CHOICES = (
    ("512x512", "512x512"),
    ("256x256", "256x256"),
)

IMAGE_QUALITY_CHOICES = (
    ("standard", "standard"),
    ("hd", "hd"),
)

IMAGE_DEFAULT_MODEL = IMAGE_MODEL_CHOICES[0][0]
IMAGE_DEFAULT_SIZE = IMAGE_SIZE_CHOICES[0][0]
IMAGE_DEFAULT_QUALITY = IMAGE_QUALITY_CHOICES[0][0]
