"""Shared constants used across the Paperbird project."""

from __future__ import annotations

DEFAULT_COLLECT_LIMIT = 100
REWRITE_MAX_ATTEMPTS = 3
OPENAI_DEFAULT_TEMPERATURE = 0.2
OPENAI_RESPONSE_FORMAT = {"type": "json_object"}

COLLECTOR_MAX_ATTEMPTS = 5
COLLECTOR_BASE_RETRY_DELAY = 30
COLLECTOR_MAX_RETRY_DELAY = 900
COLLECTOR_STALE_TIMEOUT = 600

PUBLISH_MAX_ATTEMPTS = 4
PUBLISH_BASE_RETRY_DELAY = 45
PUBLISH_MAX_RETRY_DELAY = 1800

IMAGE_MAX_ATTEMPTS = 3
IMAGE_BASE_RETRY_DELAY = 30
IMAGE_MAX_RETRY_DELAY = 900

REWRITE_BASE_RETRY_DELAY = 20
REWRITE_MAX_RETRY_DELAY = 600

REWRITE_DEFAULT_MAX_TOKENS = 1000

DEFAULT_QUEUE_MAX_ATTEMPTS = 5
DEFAULT_QUEUE_BASE_RETRY_DELAY = 10
DEFAULT_QUEUE_MAX_RETRY_DELAY = 3600
DEFAULT_QUEUE_STALE_TIMEOUT = 600

MAINTENANCE_MAX_ATTEMPTS = 3
MAINTENANCE_BASE_RETRY_DELAY = 60
MAINTENANCE_MAX_RETRY_DELAY = 3600

SOURCE_MAX_ATTEMPTS = 3
SOURCE_BASE_RETRY_DELAY = 120
SOURCE_MAX_RETRY_DELAY = 3600
COLLECTOR_WEB_STALE_TIMEOUT = 300

IMAGE_MODEL_CHOICES = (
    ("gpt-image-1", "gpt-image-1"),
    ("dall-e-3", "dall-e-3"),
    ("yandex-art", "yandex-art"),
)

IMAGE_SIZE_CHOICES = (
    ("1024x1024", "1024x1024"),
    ("1024x1536", "1024x1536"),
    ("1536x1024", "1536x1024"),
    ("auto", "auto"),
)

IMAGE_QUALITY_CHOICES = (
    ("low", "low"),
    ("medium", "medium"),
    ("high", "high"),
    ("auto", "auto"),
)

IMAGE_DEFAULT_MODEL = IMAGE_MODEL_CHOICES[0][0]
IMAGE_DEFAULT_SIZE = "1024x1024"
IMAGE_DEFAULT_QUALITY = "medium"

REWRITE_MODEL_CHOICES = (
    ("gpt-4o-mini", "gpt-4o-mini"),
    ("gpt-4o", "gpt-4o"),
    ("gpt-4.1-mini", "gpt-4.1-mini"),
    ("gpt-5", "gpt-5"),
    ("yandexgpt-lite", "yandexgpt-lite"),
    ("yandexgpt", "yandexgpt"),
)
REWRITE_DEFAULT_MODEL = REWRITE_MODEL_CHOICES[0][0]
